Revert "Update master (#1259)" (#1263)
This reverts commit 8e378b5c3a3485ab80cf7f296b666a08eac93a8e.

diff --git a/.github/workflows/nosimage.yml b/.github/workflows/nosimage.yml
--- a/.github/workflows/nosimage.yml
+++ b/.github/workflows/nosimage.yml
@@ -21,22 +21,21 @@ jobs:
     - name: Generate Examples and Check No Diff
       run: |
         cd tools/nosimage
-        go generate ./example
+        go run example/generate_example.go -file-path example/example_nosimageprofile.textproto
+        go run example/generate_example.go -file-path example/example_nosimageprofile_invalid.textproto -invalid
 
         git diff --exit-code --ignore-all-space --ignore-blank-lines
 
     - name: Validate Good Example
       run: |
         cd tools/nosimage
-        go run validate/validate.go -file example/valid_example_nosimageprofile.textproto; rm -rf tmp
+        go run validate/validate.go -file example/example_nosimageprofile.textproto; rm -rf tmp
 
     - name: Validate Bad Example
       run: |
         cd tools/nosimage
-        for file in example/invalid-*.textproto; do
-          if go run validate/validate.go -file "$file"; then
-            echo "Validation passed for $file, but failure expected"
-            exit 1
-          fi
-        done
+        if go run validate/validate.go -file example/example_nosimageprofile_invalid.textproto; then
+          echo "Validation passed, but failure expected"
+          exit 1
+        fi
         rm -rf tmp
